=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for TitleExpert::AddressNormalisationAndMatchingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AddressNormalisationAndMatchingApi' do
  before do
    # run before each test
    @instance = TitleExpert::AddressNormalisationAndMatchingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddressNormalisationAndMatchingApi' do
    it 'should create an instact of AddressNormalisationAndMatchingApi' do
      expect(@instance).to be_instance_of(TitleExpert::AddressNormalisationAndMatchingApi)
    end
  end

  # unit tests for address_match_match
  # Compares two addresses on a \&quot;logical first line and postcode\&quot; basis.
  # 
  # @param clientid Your client id.
  # @param addresses The addresses to be compared.
  # @param [Hash] opts the optional parameters
  # @return [AddressMatchResponse]
  describe 'address_match_match test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for address_match_normalise
  # Normalise an address by concatenating lines, singling multiple spaces, removing punctuation and doing things like replacing \&quot;Road\&quot; by \&quot;Rd\&quot;.
  # 
  # @param clientid Your client id.
  # @param address The address to be normalised.
  # @param [Hash] opts the optional parameters
  # @return [Address]
  describe 'address_match_normalise test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
