=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for TitleExpert::OnlineOwnershipVerificationOOVApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OnlineOwnershipVerificationOOVApi' do
  before do
    # run before each test
    @instance = TitleExpert::OnlineOwnershipVerificationOOVApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OnlineOwnershipVerificationOOVApi' do
    it 'should create an instact of OnlineOwnershipVerificationOOVApi' do
      expect(@instance).to be_instance_of(TitleExpert::OnlineOwnershipVerificationOOVApi)
    end
  end

  # unit tests for ownership_verification_acknowledge_dequeued
  # Acknowledge receipt of the result of a Request that was retrieved from the get-next-ready endpoint.
  # 
  # @param clientid Your client id.
  # @param requestid The id of the request.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'ownership_verification_acknowledge_dequeued test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ownership_verification_acknowledge_request
  # Acknowledge receipt of the result of a Request that was not retrieved from the get-next-ready endpoint.
  # 
  # @param clientid Your client id.
  # @param requestid The id of the request.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'ownership_verification_acknowledge_request test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ownership_verification_dequeue_next_ready_for_ack
  # Gets the next earliest-started Request which has finished and has not yet been Acknowledged. The request will be locked for a certain time window within which it will not be available from get-next-ready. Normally, you will Acknowledge within this time window as part of your processing of the results.
  # 
  # @param clientid Your client id.
  # @param [Hash] opts the optional parameters
  # @return [TitleDataResponse]
  describe 'ownership_verification_dequeue_next_ready_for_ack test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ownership_verification_get_response
  # Get the current status of an Online Ownership Verification request.
  # 
  # @param clientid Your client id.
  # @param requestid The id of the request.
  # @param [Hash] opts the optional parameters
  # @return [OwnerVerifyResponse]
  describe 'ownership_verification_get_response test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ownership_verification_get_results
  # Get the results of a complete Online Ownership Verification request.
  # 
  # @param clientid Your client id.
  # @param requestid The id of the request.
  # @param [Hash] opts the optional parameters
  # @return [OwnerVerifyResult]
  describe 'ownership_verification_get_results test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ownership_verification_search_requests
  # Search for Online Ownership Verification requests meeting the specified criteria.
  # 
  # @param clientid Your client id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Optional. Values allowed are: pending, complete, failed, cancelled, expired. Prepend ! to invert.
  # @option opts [String] :statussince Optional. Searches for requests whose status last changed at/after the specified UTC date/time (ISO8601/like format yyyy-MM-dd HH:mm:ss).
  # @option opts [String] :acknowledged Optional. Whether to search for requests that have (1, y, yes, true) or have not (0, n, no, false) been Acknowledged.
  # @option opts [String] :clientref Optional reference provided when request was submitted.
  # @option opts [String] :title Optional title number.
  # @option opts [String] :order Optional. Order by date request started; values allowed are: oldestfirst (default), newestfirst.
  # @option opts [String] :maxentries Optional. Limits the number of requests returned.
  # @return [Array<OwnerVerifyResponse>]
  describe 'ownership_verification_search_requests test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ownership_verification_verify_by_address
  # Issue a request for Online Ownership Verification against a property address. This will incur a charge.
  # 
  # @param clientid Your client id.
  # @param verify_request Details of the Ownership Verification request.
  # @param [Hash] opts the optional parameters
  # @return [OwnerVerifyResponse]
  describe 'ownership_verification_verify_by_address test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ownership_verification_verify_by_title
  # Issue a request for Online Ownership Verification against a known Title Number. This will incur a charge.
  # 
  # @param clientid Your client id.
  # @param verify_request Details of the Ownership Verification request.
  # @param [Hash] opts the optional parameters
  # @return [OwnerVerifyResponse]
  describe 'ownership_verification_verify_by_title test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
