=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for TitleExpert::TitleNumbersePDEnquiryByPropertyDescriptionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TitleNumbersePDEnquiryByPropertyDescriptionApi' do
  before do
    # run before each test
    @instance = TitleExpert::TitleNumbersePDEnquiryByPropertyDescriptionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TitleNumbersePDEnquiryByPropertyDescriptionApi' do
    it 'should create an instact of TitleNumbersePDEnquiryByPropertyDescriptionApi' do
      expect(@instance).to be_instance_of(TitleExpert::TitleNumbersePDEnquiryByPropertyDescriptionApi)
    end
  end

  # unit tests for title_numbers_search
  # Search for the title number(s) for an address (ePD, Enquiry by Property Description).
  # 
  # @param clientid Your client id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :bname Building name (max 50 chars). Always specify at least one of this and bno.
  # @option opts [String] :bno Building number (max 5 chars). Always specify at least one of this and bname.
  # @option opts [String] :street Street (max 80 chars). If postcode is not specified then specify both street and city.
  # @option opts [String] :city Town or city (max 35 chars). If postcode is not specified then specify both street and city.
  # @option opts [String] :postcode Full postcode, including a space separating the two parts.
  # @option opts [String] :tenure Optional comma-separated list of tenure types to filter results. Values allowed are: other, freehold, leasehold, commonhold, feuhold, mixed, unknown, unavailable, caution_against_first_registration, rent_charge, franchise, profit_a_prendre_in_gross, manor.
  # @return [TitleNumbersResult]
  describe 'title_numbers_search test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
