=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for TitleExpert::TitlePlanOC1Api
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TitlePlanOC1Api' do
  before do
    # run before each test
    @instance = TitleExpert::TitlePlanOC1Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TitlePlanOC1Api' do
    it 'should create an instact of TitlePlanOC1Api' do
      expect(@instance).to be_instance_of(TitleExpert::TitlePlanOC1Api)
    end
  end

  # unit tests for title_plan_acknowledge_dequeued
  # Acknowledge receipt of the result of a Request that was retrieved from the get-next-ready endpoint.
  # 
  # @param clientid Your client id.
  # @param requestid The id of the request.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'title_plan_acknowledge_dequeued test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for title_plan_acknowledge_request
  # Acknowledge receipt of the result of a Request that was not retrieved from the get-next-ready endpoint.
  # 
  # @param clientid Your client id.
  # @param requestid The id of the request.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'title_plan_acknowledge_request test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for title_plan_dequeue_next_ready_for_ack
  # Gets the next earliest-started Request which has finished and has not yet been Acknowledged. The request will be locked for a certain time window within which it will not be available from get-next-ready. Normally, you will Acknowledge within this time window as part of your processing of the results.
  # 
  # @param clientid Your client id.
  # @param [Hash] opts the optional parameters
  # @return [TitleDataResponse]
  describe 'title_plan_dequeue_next_ready_for_ack test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for title_plan_get_document
  # Gets the Title Plan PDF.
  # 
  # @param clientid Your client id.
  # @param requestid The id of the request.
  # @param documentid The id of the particular document.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'title_plan_get_document test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for title_plan_get_result
  # Get the current status of a Title Plan request.
  # 
  # @param clientid Your client id.
  # @param requestid The id of the request.
  # @param [Hash] opts the optional parameters
  # @return [TitlePlanResponse]
  describe 'title_plan_get_result test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for title_plan_search
  # Search for Title Plan requests meeting the specified criteria.
  # 
  # @param clientid Your client id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Optional. Values allowed are: pending, complete, failed, cancelled, expired. Prepend ! to invert.
  # @option opts [String] :statussince Optional. Searches for requests whose status last changed at/after the specified UTC date/time (ISO8601/like format yyyy-MM-dd HH:mm:ss).
  # @option opts [String] :acknowledged Optional. Whether to search for requests that have (1, y, yes, true) or have not (0, n, no, false) been Acknowledged.
  # @option opts [String] :clientref Optional client reference.
  # @option opts [String] :title Optional title number.
  # @option opts [String] :order Optional. Order by date request started; values allowed are: oldestfirst (default), newestfirst.
  # @option opts [String] :maxentries Optional. Limits the number of requests returned.
  # @return [Array<TitlePlanResponse>]
  describe 'title_plan_search test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for title_plan_submit_request
  # Issue a request for a Title Plan (OC1). Will continue if applications are pending against the Title (returning back-dated) or if closed and continued (under the new Title number). This will incur a charge.
  # 
  # @param clientid Your client id.
  # @param title_plan_request Information identifying the plan being requested.
  # @param [Hash] opts the optional parameters
  # @return [TitlePlanResponse]
  describe 'title_plan_submit_request test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
