=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::ExtraTitleNumber
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExtraTitleNumber' do
  before do
    # run before each test
    @instance = TitleExpert::ExtraTitleNumber.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExtraTitleNumber' do
    it 'should create an instact of ExtraTitleNumber' do
      expect(@instance).to be_instance_of(TitleExpert::ExtraTitleNumber)
    end
  end
  describe 'test attribute "title_number"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "register_entries"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

