=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::HistoricalMatch
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'HistoricalMatch' do
  before do
    # run before each test
    @instance = TitleExpert::HistoricalMatch.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HistoricalMatch' do
    it 'should create an instact of HistoricalMatch' do
      expect(@instance).to be_instance_of(TitleExpert::HistoricalMatch)
    end
  end
  describe 'test attribute "proprietor_from"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "proprietor_to"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

