=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::Issue
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Issue' do
  before do
    # run before each test
    @instance = TitleExpert::Issue.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Issue' do
    it 'should create an instact of Issue' do
      expect(@instance).to be_instance_of(TitleExpert::Issue)
    end
  end
  describe 'test attribute "issue_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["None", "UnableToTitleCheck", "TitleCommonhold", "DifferentTitleNumber", "IncompletePropertyAddress", "MultiplePropertyAddresses", "LeaseholdUnclear", "MultipleLeaseEntries", "LeaseDetailsNotParsable", "ScheduleOfLeases", "NoProprietorshipDate", "ProprietorIsCompany", "ChargePrioritiesChanged", "RegChargeSecondMortgage", "RegChargeProprietorNotCompany", "MultipleChargeeParties", "NoChargeDate", "NoRegistrationDate", "RegChargeSubcharge", "ExtraTitleNumber", "DeedOfPostponement", "Matrimonial", "FormARestrictionSingleProprietor", "FormPRestriction", "FormLLRestriction", "Restriction", "RightToBuyCharge", "InhibitionCaution", "OptionToPurchase", "RightOfPreEmption", "ProprietorNotice", "EquitableCharge", "NotedCharge", "FlyingFreehold", "Footprint", "GreenOutEntry", "MissingDocument", "BankruptcyNotice", "UnidentifiedEntry", "MissingLeaseDetails"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.issue_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "register_entries"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "references"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "issue_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

