=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::MatchInfo
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MatchInfo' do
  before do
    # run before each test
    @instance = TitleExpert::MatchInfo.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MatchInfo' do
    it 'should create an instact of MatchInfo' do
      expect(@instance).to be_instance_of(TitleExpert::MatchInfo)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Skipped", "None", "Partial", "Exact"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "methods"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["Distance", "Sound", "Initial", "Middle", "Alias"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.methods = value }.not_to raise_error
       #end
    end
  end

end

