=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::Q1AgreedNoticeType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Q1AgreedNoticeType' do
  before do
    # run before each test
    @instance = TitleExpert::Q1AgreedNoticeType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Q1AgreedNoticeType' do
    it 'should create an instact of Q1AgreedNoticeType' do
      expect(@instance).to be_instance_of(TitleExpert::Q1AgreedNoticeType)
    end
  end
  describe 'test attribute "agreed_notice_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Item10", "Item20"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.agreed_notice_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "agreed_notice_type_specified"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "entry_details"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

