=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::Q1DocumentEntryType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Q1DocumentEntryType' do
  before do
    # run before each test
    @instance = TitleExpert::Q1DocumentEntryType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Q1DocumentEntryType' do
    it 'should create an instact of Q1DocumentEntryType' do
      expect(@instance).to be_instance_of(TitleExpert::Q1DocumentEntryType)
    end
  end
  describe 'test attribute "document_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Item10", "Item20", "Item30", "Item40", "Item50", "Item60", "Item70", "Item80", "Item90", "Item100", "Item110", "Item120", "Item130", "Item140", "Item150", "Item160", "Item170", "Item180"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.document_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "document_date"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "entry_number"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "plan_only_indicator"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "filed_under"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "register_description"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

