=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::Q1HomeRightsType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Q1HomeRightsType' do
  before do
    # run before each test
    @instance = TitleExpert::Q1HomeRightsType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Q1HomeRightsType' do
    it 'should create an instact of Q1HomeRightsType' do
      expect(@instance).to be_instance_of(TitleExpert::Q1HomeRightsType)
    end
  end
  describe 'test attribute "change_of_address_indicator"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "home_rights_entry_details"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "change_of_address_entry_details"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

