=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::Q1PostcodeZoneType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Q1PostcodeZoneType' do
  before do
    # run before each test
    @instance = TitleExpert::Q1PostcodeZoneType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Q1PostcodeZoneType' do
    it 'should create an instact of Q1PostcodeZoneType' do
      expect(@instance).to be_instance_of(TitleExpert::Q1PostcodeZoneType)
    end
  end
  describe 'test attribute "postcode"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

