=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TitleExpert::ReturnedDocuments
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReturnedDocuments' do
  before do
    # run before each test
    @instance = TitleExpert::ReturnedDocuments.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReturnedDocuments' do
    it 'should create an instact of ReturnedDocuments' do
      expect(@instance).to be_instance_of(TitleExpert::ReturnedDocuments)
    end
  end
  describe 'test attribute "result_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Unknown", "FE", "PE", "FP", "CN", "IR"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.result_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "hmlr_reference"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "documents"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

