=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module TitleExpert
  # Data extracted about the property
  class PropertyData
    # The \"class of title code\" from the RES data, e.g. \"Qualified Freehold\"
    attr_accessor :title_code

    # The class of title, e.g. Absoulte (derived from TitleCode)
    attr_accessor :_class

    # The title tenure, e.g. Leasehold (derived from TitleCode)
    attr_accessor :tenure

    # Is this property Commonhold?
    attr_accessor :commonhold

    # 1 or more addresses for the property
    attr_accessor :addresses

    # True if ALL the property addresses are definitely something other than the main part of the property (e.g. a garage or additional land). A value of false DOES NOT guarantee that this title is for the main part of the property.
    attr_accessor :is_not_main_title

    # True if ANY of the property addresses is definitely known to be in Scotland. False if ALL the property addresses are definitely known not to be in Scotland. Null iin all other cases (typically those where a postcode is missing).
    attr_accessor :is_scottish

    # The registration date of the \"price paid\" register entry, if there is one.
    attr_accessor :purchase_register_entry_date

    # The values from the price infills (if any) of the \"price paid\" register entry, if there is one. Typically there is either a single value or two values, where two values indicates a range of prices. Null unless there is at least one price.
    attr_accessor :purchase_prices

    # The values from the date infills (if any) of the \"price paid\" register entry, if there is one. Null unless there is at least one date.
    attr_accessor :purchase_dates

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'title_code' => :'TitleCode',
        :'_class' => :'Class',
        :'tenure' => :'Tenure',
        :'commonhold' => :'Commonhold',
        :'addresses' => :'Addresses',
        :'is_not_main_title' => :'IsNotMainTitle',
        :'is_scottish' => :'IsScottish',
        :'purchase_register_entry_date' => :'PurchaseRegisterEntryDate',
        :'purchase_prices' => :'PurchasePrices',
        :'purchase_dates' => :'PurchaseDates'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'title_code' => :'String',
        :'_class' => :'String',
        :'tenure' => :'String',
        :'commonhold' => :'BOOLEAN',
        :'addresses' => :'Array<Address>',
        :'is_not_main_title' => :'BOOLEAN',
        :'is_scottish' => :'BOOLEAN',
        :'purchase_register_entry_date' => :'DateTime',
        :'purchase_prices' => :'Array<Float>',
        :'purchase_dates' => :'Array<DateTime>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'TitleCode')
        self.title_code = attributes[:'TitleCode']
      end

      if attributes.has_key?(:'Class')
        self._class = attributes[:'Class']
      end

      if attributes.has_key?(:'Tenure')
        self.tenure = attributes[:'Tenure']
      end

      if attributes.has_key?(:'Commonhold')
        self.commonhold = attributes[:'Commonhold']
      end

      if attributes.has_key?(:'Addresses')
        if (value = attributes[:'Addresses']).is_a?(Array)
          self.addresses = value
        end
      end

      if attributes.has_key?(:'IsNotMainTitle')
        self.is_not_main_title = attributes[:'IsNotMainTitle']
      end

      if attributes.has_key?(:'IsScottish')
        self.is_scottish = attributes[:'IsScottish']
      end

      if attributes.has_key?(:'PurchaseRegisterEntryDate')
        self.purchase_register_entry_date = attributes[:'PurchaseRegisterEntryDate']
      end

      if attributes.has_key?(:'PurchasePrices')
        if (value = attributes[:'PurchasePrices']).is_a?(Array)
          self.purchase_prices = value
        end
      end

      if attributes.has_key?(:'PurchaseDates')
        if (value = attributes[:'PurchaseDates']).is_a?(Array)
          self.purchase_dates = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @title_code.nil?
        invalid_properties.push("invalid value for 'title_code', title_code cannot be nil.")
      end

      if @_class.nil?
        invalid_properties.push("invalid value for '_class', _class cannot be nil.")
      end

      if @tenure.nil?
        invalid_properties.push("invalid value for 'tenure', tenure cannot be nil.")
      end

      if @commonhold.nil?
        invalid_properties.push("invalid value for 'commonhold', commonhold cannot be nil.")
      end

      if @addresses.nil?
        invalid_properties.push("invalid value for 'addresses', addresses cannot be nil.")
      end

      if @is_not_main_title.nil?
        invalid_properties.push("invalid value for 'is_not_main_title', is_not_main_title cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @title_code.nil?
      return false if @_class.nil?
      _class_validator = EnumAttributeValidator.new('String', ["Other", "Absolute", "Possessory", "Qualified", "Good"])
      return false unless _class_validator.valid?(@_class)
      return false if @tenure.nil?
      tenure_validator = EnumAttributeValidator.new('String', ["Other", "Freehold", "Leasehold"])
      return false unless tenure_validator.valid?(@tenure)
      return false if @commonhold.nil?
      return false if @addresses.nil?
      return false if @is_not_main_title.nil?
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] _class Object to be assigned
    def _class=(_class)
      validator = EnumAttributeValidator.new('String', ["Other", "Absolute", "Possessory", "Qualified", "Good"])
      unless validator.valid?(_class)
        fail ArgumentError, "invalid value for '_class', must be one of #{validator.allowable_values}."
      end
      @_class = _class
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] tenure Object to be assigned
    def tenure=(tenure)
      validator = EnumAttributeValidator.new('String', ["Other", "Freehold", "Leasehold"])
      unless validator.valid?(tenure)
        fail ArgumentError, "invalid value for 'tenure', must be one of #{validator.allowable_values}."
      end
      @tenure = tenure
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          title_code == o.title_code &&
          _class == o._class &&
          tenure == o.tenure &&
          commonhold == o.commonhold &&
          addresses == o.addresses &&
          is_not_main_title == o.is_not_main_title &&
          is_scottish == o.is_scottish &&
          purchase_register_entry_date == o.purchase_register_entry_date &&
          purchase_prices == o.purchase_prices &&
          purchase_dates == o.purchase_dates
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [title_code, _class, tenure, commonhold, addresses, is_not_main_title, is_scottish, purchase_register_entry_date, purchase_prices, purchase_dates].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = TitleExpert.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
