=begin
#ACS Title Expert

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module TitleExpert
  # Information that has been extracted from the RES return.
  class TitleDataExtract
    # The title number of the returned OC (not necessarily the same as the title number asked for)
    attr_accessor :title_number

    # The OC date/time
    attr_accessor :oc_date_time

    # The edition date
    attr_accessor :edition_date

    # The district (always present)
    attr_accessor :district

    # The administrative area (always present)
    attr_accessor :adminstrative_area

    # The LR office name (always present)
    attr_accessor :lr_office_name

    # Data extracted about the property (always present)
    attr_accessor :property_data

    # Data extracted about the leases, each corresponding to the same entry from the RES summary. Present only if this is a leasehold property (when it may be an empty array), otherwise null.
    attr_accessor :leases

    # Null if the OC contains no schedules of leases, otherwise 0 or more \"schedules\" (where a \"schedule\" is defined as a Schedule entry (i.e. an entry of type Q1ScheduleType) in any of the Property, Proprietorship and Charges Registers whose \"ScheduleType\" is the text \"SCHEDULE OF NOTICES OF LEASE\"). An empty array means that the \"schedule of leases\" is actually just an ordinary entry in the Charges Register.
    attr_accessor :schedules_of_leases

    # Data extracted about the proprietor(s) (always present)
    attr_accessor :proprietors_data

    # Data extracted about the registered charges if any, or null if there are no registered charges
    attr_accessor :registered_charges_data

    # Details of 1 or more \"extra title numbers\" found, or null if no extra title numbers were found. An \"extra title number\" is a title number mentioned in the OC which is likely to be \"relevant\" when doing something involving the current title number.
    attr_accessor :extra_title_numbers

    # The register entries that were identified as Form A restrictions, or null if no Form A restrictions were found.
    attr_accessor :form_a_restrictions

    # Details of 1 or more Form P restrictions found, or null if no Form P restrictions were found.
    attr_accessor :form_p_restrictions

    # Data extracted about the documents referred to on the register, or null if no such documents were found.
    attr_accessor :documents


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'title_number' => :'TitleNumber',
        :'oc_date_time' => :'OCDateTime',
        :'edition_date' => :'EditionDate',
        :'district' => :'District',
        :'adminstrative_area' => :'AdminstrativeArea',
        :'lr_office_name' => :'LROfficeName',
        :'property_data' => :'PropertyData',
        :'leases' => :'Leases',
        :'schedules_of_leases' => :'SchedulesOfLeases',
        :'proprietors_data' => :'ProprietorsData',
        :'registered_charges_data' => :'RegisteredChargesData',
        :'extra_title_numbers' => :'ExtraTitleNumbers',
        :'form_a_restrictions' => :'FormARestrictions',
        :'form_p_restrictions' => :'FormPRestrictions',
        :'documents' => :'Documents'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'title_number' => :'String',
        :'oc_date_time' => :'DateTime',
        :'edition_date' => :'DateTime',
        :'district' => :'String',
        :'adminstrative_area' => :'String',
        :'lr_office_name' => :'String',
        :'property_data' => :'PropertyData',
        :'leases' => :'Array<Lease>',
        :'schedules_of_leases' => :'Array<ScheduleOfLeases>',
        :'proprietors_data' => :'ProprietorsData',
        :'registered_charges_data' => :'RegisteredChargesData',
        :'extra_title_numbers' => :'Array<ExtraTitleNumber>',
        :'form_a_restrictions' => :'Array<RegisterEntry>',
        :'form_p_restrictions' => :'Array<FormPRestriction>',
        :'documents' => :'Array<Document>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'TitleNumber')
        self.title_number = attributes[:'TitleNumber']
      end

      if attributes.has_key?(:'OCDateTime')
        self.oc_date_time = attributes[:'OCDateTime']
      end

      if attributes.has_key?(:'EditionDate')
        self.edition_date = attributes[:'EditionDate']
      end

      if attributes.has_key?(:'District')
        self.district = attributes[:'District']
      end

      if attributes.has_key?(:'AdminstrativeArea')
        self.adminstrative_area = attributes[:'AdminstrativeArea']
      end

      if attributes.has_key?(:'LROfficeName')
        self.lr_office_name = attributes[:'LROfficeName']
      end

      if attributes.has_key?(:'PropertyData')
        self.property_data = attributes[:'PropertyData']
      end

      if attributes.has_key?(:'Leases')
        if (value = attributes[:'Leases']).is_a?(Array)
          self.leases = value
        end
      end

      if attributes.has_key?(:'SchedulesOfLeases')
        if (value = attributes[:'SchedulesOfLeases']).is_a?(Array)
          self.schedules_of_leases = value
        end
      end

      if attributes.has_key?(:'ProprietorsData')
        self.proprietors_data = attributes[:'ProprietorsData']
      end

      if attributes.has_key?(:'RegisteredChargesData')
        self.registered_charges_data = attributes[:'RegisteredChargesData']
      end

      if attributes.has_key?(:'ExtraTitleNumbers')
        if (value = attributes[:'ExtraTitleNumbers']).is_a?(Array)
          self.extra_title_numbers = value
        end
      end

      if attributes.has_key?(:'FormARestrictions')
        if (value = attributes[:'FormARestrictions']).is_a?(Array)
          self.form_a_restrictions = value
        end
      end

      if attributes.has_key?(:'FormPRestrictions')
        if (value = attributes[:'FormPRestrictions']).is_a?(Array)
          self.form_p_restrictions = value
        end
      end

      if attributes.has_key?(:'Documents')
        if (value = attributes[:'Documents']).is_a?(Array)
          self.documents = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @title_number.nil?
        invalid_properties.push("invalid value for 'title_number', title_number cannot be nil.")
      end

      if @oc_date_time.nil?
        invalid_properties.push("invalid value for 'oc_date_time', oc_date_time cannot be nil.")
      end

      if @edition_date.nil?
        invalid_properties.push("invalid value for 'edition_date', edition_date cannot be nil.")
      end

      if @district.nil?
        invalid_properties.push("invalid value for 'district', district cannot be nil.")
      end

      if @lr_office_name.nil?
        invalid_properties.push("invalid value for 'lr_office_name', lr_office_name cannot be nil.")
      end

      if @property_data.nil?
        invalid_properties.push("invalid value for 'property_data', property_data cannot be nil.")
      end

      if @proprietors_data.nil?
        invalid_properties.push("invalid value for 'proprietors_data', proprietors_data cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @title_number.nil?
      return false if @oc_date_time.nil?
      return false if @edition_date.nil?
      return false if @district.nil?
      return false if @lr_office_name.nil?
      return false if @property_data.nil?
      return false if @proprietors_data.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          title_number == o.title_number &&
          oc_date_time == o.oc_date_time &&
          edition_date == o.edition_date &&
          district == o.district &&
          adminstrative_area == o.adminstrative_area &&
          lr_office_name == o.lr_office_name &&
          property_data == o.property_data &&
          leases == o.leases &&
          schedules_of_leases == o.schedules_of_leases &&
          proprietors_data == o.proprietors_data &&
          registered_charges_data == o.registered_charges_data &&
          extra_title_numbers == o.extra_title_numbers &&
          form_a_restrictions == o.form_a_restrictions &&
          form_p_restrictions == o.form_p_restrictions &&
          documents == o.documents
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [title_number, oc_date_time, edition_date, district, adminstrative_area, lr_office_name, property_data, leases, schedules_of_leases, proprietors_data, registered_charges_data, extra_title_numbers, form_a_restrictions, form_p_restrictions, documents].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = TitleExpert.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
